### PR TITLE
propagate getters and setters

### PR DESCRIPTION
**Pull request by bpneal**
propagate getters and setters for value and selection Start/End, and focus / blur functions

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
Hi @bpneal, what's your need behind this?
I think you could achieve the same by simply using a `ref` on `TextareaAutosize` in your component :)

```jsx
<TextareaAutosize ref='myTextarea' />
```

```js
const myTextarea = ReactDOM.findDOMNode(this.refs.myTextarea);

myTextarea.selectionStart
myTextarea.value
myTextarea.focus()
...
```

**Comment by bpneal** [comment]
It makes the `<TextareaAutosize />` component act more like the native `<textarea />` and makes dealing with the different components more fluid.

For example if you wanted to swap out textareas for the autosize component, you wouldn't have to change how you interact with it.

**Comment by cameackeSEL** [comment]
@FrancescoCioria , the code you suggested works, but it brings up deprecation warnings on several eslinters.

The recommended way to get a ref per [react best practice](https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element) is more like this:

```
<TextareaAutosize ref={(input) => { this.textArea = input; }} />

this.textArea.selectionStart
this.textArea.value
this.textArea.focus()
...
```

**Comment by bpneal** [comment]
Thank you for your comments

**Pull request closed without merging**
