### PR TITLE
Handle all possible ref types

### LINKED ISSUE #141: Failed prop type: Invalid prop `innerRef` of type `function` supplied to `TextareaAutosizeClass`, expected `object`
With version:

```
"react-autosize-textarea": "^7.0.0",
```

I'm trying to replace my `textarea` with `TextareaAutosize`, which should work without changes as per the documentation:

Before:

```typescript
type IBodyInputProps = IInputProps & StyledComponentPropsWithRef<"textarea">

const BodyInput = styled<React.FC<IBodyInputProps>>(
  forwardRef(
    (
      {
        validationError,
        ...rest
      },
      ref: React.Ref<HTMLTextAreaElement>
    ) => (
      <textarea ref={ref} {...rest} />
    )
  )
)`
grid-column: 1 / 2;
grid-row: 1 / 2;
`
```

This works fine. After:

```typescript
type IBodyInputProps = IInputProps & StyledComponentPropsWithRef<"textarea">

const BodyInput = styled<React.FC<IBodyInputProps>>(
  forwardRef(
    (
      {
        validationError,
        ...rest
      },
      ref: React.Ref<HTMLTextAreaElement>
    ) => (
      <TextareaAutosize ref={ref} {...rest} />
    )
  )
)`
grid-column: 1 / 2;
grid-row: 1 / 2;
`
```

Gives me this error:

```
index.js:1375 Warning: Failed prop type: Invalid prop `innerRef` of type `function` supplied to `TextareaAutosizeClass`, expected `object`.
    in TextareaAutosizeClass (created by ForwardRef)
    in ForwardRef (at EditableBubbleComment.tsx:448)
    in ForwardRef (created by Context.Consumer)
    in StyledComponent (created by Styled(Component))
    in Styled(Component) (at EditableBubbleComment.tsx:211)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (at EditableBubbleComment.tsx:210)
    in form (created by Context.Consumer)
    in StyledComponent (created by styled.form)
    in styled.form (at EditableBubbleComment.tsx:204)
    in EditableBubbleComment (at ConversationThread.tsx:354)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (at ConversationThread.tsx:310)
    in div (at ConversationThread.tsx:456)
    in ForwardRef (created by Context.Consumer)
    in StyledComponent (created by Styled(Component))
    in Styled(Component) (at ConversationThread.tsx:293)
    in ForwardRef
    in ForwardRef (at Sidepanel.tsx:118)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (at Sidepanel.tsx:87)
    in Sidepanel (created by Context.Consumer)
    in StyledComponent (created by Styled(Component))
    in Styled(Component) (at Editor.tsx:246)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (at Editor.tsx:213)
    in EditorView (at App.tsx:48)
    in App (at src/index.tsx:37)
    in Provider (at src/index.tsx:35)
    in ErrorBoundary (at src/index.tsx:34)
```

### PR DESCRIPTION
**Pull request by Pajn**
Closes [#2520514](https://buildo.kaiten.io/space/32111/card/2520514)

⚠️ The line above was added during the automatic migration of all github project issues to Kaiten. The old GH issue link is kept here for reference (it is now deprecated, continue follow the original issue on Kaiten).

fixes #141 

@tommedema I published this PR as @pajn/react-autosize-textarea as quick workaround for me, hoefully it will help you too.

### CODE REVIEW

**Comment by tommedema** [comment]
Thanks @Pajn 
@giogonzo do you plan to merge this?

**Comment by giogonzo** [comment]
Hi @tommedema @Pajn and thanks for the PR. If you could provide a few details on how did you test the changes, what's the rationale, etc., it would help greatly in having this merged and released soon

**Review by giogonzo — APPROVED** [review]
LGTM

**Comment by giogonzo** [comment]
Thank you @Pajn , released as version `7.1.0`

**Pull request merged**
