### PR TITLE
#13: remove react 0.14 warnings (closes #13)

### LINKED ISSUE #13: remove react 0.14 warnings
## requirements
remove this warning:
```
Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```

## specs

- push a breaking change and update peerDependencies
- tag current master as `react-0.13`

### PR DESCRIPTION
**Pull request by giogonzo**
Issue #13

### CODE REVIEW

**Comment by gabro** [comment]
This drops the compatibility of react 0.13. Is it intented?

**Comment by giogonzo** [comment]
if you have to require either `react-dom` or `react` there's no way to be compatible?

I've pushed a tag anyway, ideally we should only backport bugfixes in the 0.13 version

**Comment by gabro** [comment]
compatible without warnings, no, probably not.
I would make clear that this breaks the compatibility in the release notes. Just that

**Comment by giogonzo** [comment]
sure, 👍

**Pull request merged**
