### PR TITLE
always skip first frames

### LINKED ISSUE #71: Wrong initial height when using StyledComponents
## description
The initial height is always rendered wrongly when using [`StyledComponents`](https://www.styled-components.com/)

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
[`StyledComponents`](https://www.styled-components.com/) adds the style asynchronously while we run `autosize` immediately in `componentDidMount` -> let's run it with a `setTimeout` as we're already doing when `maxRows` props is passed

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by hitmands**
Closes #71 
this will help to properly determinate height for the textarea.

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
Hi @hitmands,

Can you make an example where the current logic fails? Why do you think we should always skip the first render?

**Comment by hitmands** [comment]
I have something like this:

```javascript
import ReactDOM from 'react-dom';
import TextareaAutosize from 'react-autosize-textarea';

function getLineHeight(arg) {
  const data = {
    normal: 3
  }
  return data[arg];
}

const textarea = styled(TextareaAutosize)`
  line-height: ${getLineHeight('normal')};
`;

```
Always rendered wrongly, but if you add **`maxRows=1000`** then you will hit the branch which implements the timeout and **everything will just work fine**.

**Comment by FrancescoCioria** [comment]
I've some trouble reproducing this...
I've tried the plain version of your snippet and it works:
```js
<TextareaAutosize style={{ lineHeight: 3 }} />
```

Do you know if your `styled` function add the style asynchronously?
That would explain why it doesn't work

**Comment by hitmands** [comment]
Hi, `styled` comes from [`StyledComponents`](https://www.styled-components.com/) and it probably does something async. The resting part of that code is absolutely sync.

**Comment by FrancescoCioria** [comment]
Ok @hitmands let's try this, worst case scenario we'll revert the change :)

PS: the CI is complaining with this lint error: `34:1  error  Trailing spaces not allowed  no-trailing-spaces` can you fix it?

(you can run `npm run lint` locally to reproduce the error)

**Comment by FrancescoCioria** [comment]
closing in favour of #85

**Pull request closed without merging**
